"""Agent 层与 core 实现之间的端口契约（只描述“需要什么”，不定义“怎么做”）。"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class PromptPort(Protocol):
    """拿到当前轮次的系统提示与上下文消息，并推断任务协议集合。"""

    def build(self, profile: str, *, recovery: bool = False, final: bool = False) -> list: ...

    def protocols_for(self, text: str) -> list: ...

    def is_development_continuation(self, text: str, active_task) -> bool: ...

    def accepts_default_plan(self, text: str) -> bool: ...

    def requests_development_execution(self, text: str, protocols) -> bool: ...


@runtime_checkable
class DocsPort(Protocol):
    """项目工作记忆（agent_docs）访问端口。"""

    def exists(self) -> bool: ...

    def manager(self) -> Any: ...

    def begin_task(self, objective, *, run_id=None) -> dict: ...

    def record_tool(self, name: str, result: dict, args: dict) -> None: ...

    def active_task(self) -> dict | None: ...

    def finish_run(self, status: str, answer: str = "") -> dict | None: ...

    def finish(self, status: str, answer: str = "") -> None: ...


@runtime_checkable
class ToolPort(Protocol):
    """拿到工具定义、执行调用并记录结果。"""

    def definitions(self) -> list: ...

    def execute(self, call: dict, approved: str | None = None) -> dict: ...

    def error(self, call: dict, code: str, message: str, retryable: bool = False) -> dict: ...

    def reject(self, call: dict) -> dict: ...

    def confirmation_message(self, name: str) -> str: ...


@runtime_checkable
class SessionPort(Protocol):
    """会话持久化与脱敏事件记录端口。"""

    @property
    def data(self) -> dict: ...

    def save(self) -> None: ...

    def event(self, kind: str, **metadata) -> None: ...


@runtime_checkable
class DevelopmentPort(Protocol):
    """开发验证策略端口：判定验证时机并驱动验证/必须写工具的恢复流程。"""

    def should_auto_verify(self, state: dict) -> bool: ...

    def requires_change_verification(self, tool_name: str, result: dict | None = None, *, run_state: dict | None = None) -> bool: ...

    def development_change_required(self, state: dict) -> bool: ...

    def recover_tool_required(self, runner: Any) -> Any: ...

    def inject_verification_test(self, runner: Any) -> Any: ...